server:
  port: 38108

logging:
  level:
    com.lgcms.leveltest.service: DEBUG
    org.springframework.ai: DEBUG

spring:
  config:
    activate:
      on-profile: local

  ai:
    bedrock:
      aws:
        region: ap-northeast-2
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      converse:
        chat:
          options:
            model: anthropic.claude-3-haiku-20240307

  datasource:
    url: jdbc:postgresql://localhost:38121/leveltest
    username: lgcms
    password: 1234

  data:
    redis:
      host: localhost
      port: 38122
      database: 15

  kafka:
    bootstrap-servers: localhost:38123